### ISSUE TITLE
Task assignment and due dates for Milestone 2

### ISSUE THREAD

**Issue by zackt113** [UBC-MDS/movielover_py#13]
Milestone 2:
- [x]  structure, sidebars  @zjr-mds      
**Expected due: Monday**
- [x] bar chart  @adrianne-l       
 **Expected due: Tuesday**
- [x] scatterplot @zackt113    
**Expected due: Wednesday**
- [x] line chart: x axis: year, y axis: average US Revenue @lipcai   
**Expected due: Thursday**
- [x] development to Heroku  @zjr-mds   
**Expected due: Monday**
 - [x] reflection @zackt113  
 **Expected due: Thursday night**
- [x] improve readme @zackt113  and lipcai 
**Expected due: Thursday night**
- [x] final edit readme for updated changes in the dash @everyone   
**Expected due: Thursday night**

Meeting for final check: **Friday at 2 pm**!

**Comment by zackt113** [comment]
Well done for Milestone 2. Thank you, Guys!
