### ISSUE TITLE
Milestone1 task checklist

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/movielover_py#2]
Submission
- [x] repolink + team contract [@zjr-mds](https://ubc-mds.slack.com/team/U02DJ56H6RE) https://docs.google.com/document/d/1ANXtaNkJctWvbY645RifauygL7fTx1bi7hMorufJwOg/edit

Setup:
- [x] Create repo structure [@adrianne-l ]

Proposal:
- [x] section 1: motivation and purpose; North America audience [@zackt113 ]
- [x] section 2: Data description and mentioning about the filtered data (only the ones after 1980)  [@lipcai ]
       https://github.com/vega/vega-datasets/blob/next/data/movies.json 
 - [x] section 3: research question and usage scenarios: using `US-gross revenue`, `runtime`, and `rating` to find the relationship between ratings and runtime, top-rated movies based on year or genre, and revenue with genres [@adrianne-l ]

Description:
- [x] app sketch + description:  3 visulizations with bar + scatter plot + table of top-rated movies(ranking, titles, rating(or duration), MPAA Rating) [@zjr-mds]
