### ISSUE TITLE
Milestone 3 checklist

### ISSUE THREAD

**Issue by adrianne-l** [UBC-MDS/movielover_py#47]
Milestone 3:
- [x]  Python docker @adrianne-l @zjr-mds 
- [x]  Python favicon and a title to the app @adrianne-l 
- [x]  Peer review for Group 22 @zackt113 
- [x]  DashR- repo structure (copy and paste from Python) - movielover_R @zjr-mds 
- [x]  Comparing technologies (eg. Dash reactivity for our group)  @lipcai 
- [x]  Submission Milestone 3 @adrianne-l 

** Expected due on Friday afternoon** 

Meeting: **Friday 5pm**!
